### ISSUE TITLE
Extremely slow discovery majority resources missing many 500s 

### ISSUE THREAD

**Issue by mgubik** [awslabs/workload-discovery-on-aws#285]
Hello,

We deployed using the CF stack and the discovery is extremely slow and after some time gets stuck. I did check for 500s in the gremlin app and there are thousands 500s with this content:

2022-04-09T11:57:23.047Z	4ffc6e88-4ace-471d-bee0-08ab9c3bc72e	INFO	ResponseError: Server error: {
    "requestId": "b7c8f67c-3009-409a-be51-7afb019d931a",
    "detailedMessage": "The traversal has tried to use a null or non-existent value in the step: [GraphStep(vertex,[a41ec8dbaf8230e0909a017f383de747])]",
    "code": "IllegalArgumentException"
} (500)
    at Connection._handleMessage (/var/task/node_modules/gremlin/lib/driver/connection.js:282:9)
    at WebSocket.<anonymous> (/var/task/node_modules/gremlin/lib/driver/connection.js:130:43)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.emit (domain.js:475:12)
    at Receiver.receiverOnMessage (/var/task/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:400:28)
    at Receiver.emit (domain.js:475:12)
    at Receiver.dataMessage (/var/task/node_modules/ws/lib/receiver.js:413:14)
    at /var/task/node_modules/ws/lib/receiver.js:379:23
    at /var/task/node_modules/ws/lib/permessage-deflate.js:298:9

I am attaching discovery ecs task logs as requested.

[log-events-viewer-result.csv](https://github.com/awslabs/aws-perspective/files/8456931/log-events-viewer-result.csv)

Thanks Micky

**Comment by kodyabbott** [comment]
> If you are importing a large number of accounts at once, the discovery process might become slow. This often happens due to API rate limiting while it tries to discover resources. We recommend that if this occurs, that you add Regions in a gradual manner allowing the discovery process to run fully on those Regions, before attempting to add more.
> 
> The number of Regions that can be added at once will depend on how many resources they contain. 

[Source](https://docs.aws.amazon.com/solutions/latest/workload-discovery-on-aws/discovery-process-is-slow.html)

**Comment by svozza** [comment]
This issue is a scaling limitation with v1.x.x as the discovery process made an API call to AWS Config for every resource it found. For regions with ~2500 resources, this meant Config would start applying rate limiting to these calls and eventually the whole discovery process would hang and not complete. We have addressed this issue in version v2.0.0 and now make far fewer calls to Config when discovering resources. This new version was [released](https://aws.amazon.com/solutions/implementations/workload-discovery-on-aws/) today, and the 2500 resource limit no longer applies.
