### ISSUE TITLE
Transit gateway support missing and additional info about VPC and it's subnets

### ISSUE THREAD

**Issue by harrywer** [awslabs/workload-discovery-on-aws#292]
1 - it seems to not support transit gateway and its attachments

2 - it doesn't seem to be giving additional information about vpc and subnets like CIDR ranges etc

**Comment by svozza** [comment]
1. AWS Config added support for transit gateway recently, and a such we can ingest this resource type in v2.0.0 that was released today. Unfortunately due to an API limitation on our backend, we do not show the cross region relationship. We will will address this in a future version of Workload Discovery.

2. VPCs and subnets are generally rendered as bounding boxes on the frontend so you cannot access the raw data like you can with other resource types when you select them. In a future version of WD you will be able to select the bounding box and inspect the raw data.
