### ISSUE TITLE
AWS aggregator and AWS Perspective is not in sync

### ISSUE THREAD

**Issue by citylineclark** [awslabs/workload-discovery-on-aws#309]
**Describe the bug**
The AWS aggregator created by the AWS perspective template shows the correct number of resources, but not all of these resources are not reflected in AWS Perspective UI.

I was able to add 3 regions / 2 accounts successfully. When I try to add another region/account, the servers are no longer reflected in AWS Perspective UI even though they are discovered by the aggregator. So right now, the number of EC2 instances in AWS config aggregator is not the same as the number of EC2 instances in AWS Perspective. 

The scheduled ECS task aws-perspective-xxxx-cluster will finish execution. However, when you look at cloudwatch aws-perspective-xxx-task log, you can see this error.
`{
    "level": "error",
    "message": "callAwsApiWithPagination with selectResourceConfig error:",
    "timestamp": "2022-10-05T08:33:50.690Z"
}
{
    "level": "error",
    "message": "Error Message: The security token included in the request is invalid",
    "timestamp": "2022-10-05T08:33:50.690Z"
}
`
In AWS Perspective, the last-scanned field of newly added region/account is always "N/A"

**Comment by svozza** [comment]
This issue is a scaling limitation with v1.x.x as the discovery process made an API call to AWS Config for every resource it found. For regions with ~2500 resources, this meant Config would start applying rate limiting to these calls and eventually the whole discovery process would hang and not complete. We have addressed this issue in version v2.0.0 and now make far fewer calls to Config when discovering resources. This new version was [released](https://aws.amazon.com/solutions/implementations/workload-discovery-on-aws/) today, and the 2500 resource limit no longer applies.
